#!/usr/bin/env bash

render_command() {
  local tree_connector="$1"
  local subcommand="$2"
  local arguments="${3:-}"

  printf ' %s 🟢 **/groot-queue** `%s`%s\n' "$tree_connector" "$subcommand" "$arguments"
}

printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
printf " ¿Qué querés hacer hoy?\n"
printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
printf "\n"
printf " 🚀 EMPEZAR\n"
printf " │\n"
render_command "├─" "setup"
printf " │     → ¿Primera vez usando esta tool? Corré esto para configurar tu entorno.\n"
printf " │\n"
render_command "├─" "list"
printf " │     → Mirá qué tickets están abiertos ahora mismo en la cola.\n"
printf " │\n"
render_command "└─" "stats"
printf "\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0→ Necesitás un resumen rápido de cómo está la cola hoy.\n"
printf "\n"
printf " 🔍 INVESTIGAR\n"
printf " │\n"
render_command "├─" "classify"
printf " │     → Agrupá los tickets por tipo de problema y urgencia de un vistazo.\n"
printf " │\n"
render_command "├─" "detail" " <SSHP-XXXXXX>"
printf " │     → Profundizá en un ticket puntual: qué pasó, clasificación y sugerencia.\n"
printf " │\n"
render_command "└─" "solve" " <SSHP-XXXXXX>"
printf "\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0→ ¿No sabés cómo resolver un ticket? Te sugiero una solución paso a paso.\n"
printf "\n"
printf " ⚡ ACTUAR\n"
printf " │\n"
render_command "├─" "assign-unassigned"
printf " │     → Repartí equitativamente los tickets sin dueño entre el equipo.\n"
printf " │\n"
render_command "├─" "derive" " <SSHP-XXXXXX>"
printf " │     → Este ticket no es nuestro — derivalo al equipo correcto.\n"
printf " │\n"
render_command "├─" "discard" " <SSHP-XXXXXX>"
printf " │     → El ticket no corresponde a soporte Groot — cerralo con justificación.\n"
printf " │\n"
render_command "└─" "backfill-guides"
printf "\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0→ Posteá guías de resolución en tickets asignados que todavía no tienen una.\n"
printf "\n"
printf " 🚨 ALERTAS\n"
printf " │\n"
render_command "└─" "alerts"
printf "\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0→ ¿Algún ticket está por romper SLA? Detectalos y notificá por Slack.\n"
printf "\n"
printf " 📚 KNOWLEDGE BASE\n"
printf " │\n"
render_command "├─" "save" " <SSHP-XXXXXX> <desc>"
printf " │     → Resolviste un ticket? Guardá la solución para que el equipo la reutilice.\n"
printf " │\n"
render_command "├─" "add-rule"
printf " │     → Agregá una nueva regla de triage para mejorar la clasificación automática.\n"
printf " │\n"
render_command "└─" "analyze-history"
printf "\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0→ Analizá tickets cerrados y extraé patrones para nutrir la knowledge base.\n"
printf "\n"
printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
printf ' 💡 Tip: ¿No sabés por dónde empezar? Corré `/groot-queue setup`.\n'
printf "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
